[package]
name = "fuzz-mutator-entry-data-structured"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
genlayer_calldata = { path = "../../../crates/calldata", features = [
    "fuzzing",
] }
genvm-fuzzing = { path = "../../../../../../crates/fuzzing" }
