[package]
name = "genlayer_calldata_derive"
version = "0.0.1"
edition = "2024"
repository = "https://github.com/genlayerlabs/genvm"
description = "Derive macros for genlayer_calldata Encode/Decode traits"
license-file = "../calldata/LICENSE.txt"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
