[package]
name = "genlayer_calldata"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/genlayerlabs/genvm"
description = "Crate for handling GenLayer calldata encoding and decoding"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://genlayer.com"
keywords = ["genlayer", "blockchain", "smart-contracts", "wasm", "wasi"]
categories = ["encoding", "parser-implementations"]
exclude = [
    "/tests/**", "/fuzz/**"
]

[[example]]
name = "fuzz-genvm-common-decode"
path = "fuzz/genvm-common-decode.rs"

[[example]]
name = "fuzz-genvm-common-encode"
path = "fuzz/genvm-common-encode.rs"
required-features = ["arbitrary"]

[features]
default = []
arbitrary = ["dep:arbitrary"]

[dependencies]
genlayer_calldata_derive = { path = "../calldata-derive" }
hex = "0.4.3"
num-bigint = {version = "0.4.6", features = ["serde"] }
sha3 = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
arbitrary = { version = "1.0", optional = true }
primitive-types = { version = "0.13", features = ["impl-serde"] }
bytes = {version = "1.11.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
afl = { version = "0.15.18", features = ["no_cfg_fuzzing"] }
hex = "0.4.3"
