[package]
name = "fuzz-mutator-runners-parse-structured"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
genvm-fuzzing = { path = "../../../../../../crates/fuzzing" }
serde = { version = "1.0.219", features = ["derive"] }

[dependencies.mutatis]
default-features = false
features = ["derive", "std"]
version = "0.5.3"
