[package]
name = "genvm-common"
version = "0.3.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
genlayer_calldata = { path = "../calldata" }
genlayer_sdk = { path = "../sdk-rs", default-features = false, features = [
    "arbitrary",
] }
genvm_modules_interfaces = { path = "../modules-interfaces" }

anyhow = { version = "1.0.97", features = ["backtrace"] }
arbitrary = "1.4.2"
archery = "1.2.2"
bytes = { version = "1.11.0", features = ["serde"] }
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.35", features = ["derive"] }
crossbeam = "0.8.4"
dashmap = "6.1.0"
hex = "0.4.3"
libc = "0.2"
num-bigint = { version = "0.4.6", features = ["serde"] }
num-rational = { version = "0.4", default-features = false, features = [
    "num-bigint",
] }
num-traits = "0.2"
primitive-types = { version = "0.13.1", default-features = false, features = [
    "impl-serde",
    "std",
] }
regex = "1.11.1"
rpds = "1.2.0"
rustix = { version = "0.38.44", features = [
    "mm",
    "std",
], default-features = false }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_bytes = "0.11.17"
serde_json = "1.0.140"
serde_yaml = "0.9.34"
symbol_table = { version = "0.4.0", features = ["global"] }
thiserror = "2.0.18"
tokio = { version = "1.44.1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
    "sync",
], default-features = false }
